default_platform(:ios)

platform :ios do
  desc "Build and sign beta version for Apple TestFlight"
  lane :beta do
    build_app(
      project: "App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_testflight
  end

  desc "Deploy release to App Store Connect"
  lane :release do
    build_app(
      project: "App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end
end
